services:
  db:
    image: postgres:15-alpine
    container_name: n3-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: n3_db
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: n3-api-service
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/n3_db
    depends_on:
      - db